all: ctmconv

OPENCTMDIR = ../src
OPENCTMLIB = $(OPENCTMDIR)/libopenctm.a

ctmconv: ctmconv.cpp ply.cpp ply.h $(OPENCTMLIB)
	g++ -s -O2 -W -I$(OPENCTMDIR) -o $@ -L$(OPENCTMDIR) ctmconv.cpp ply.cpp -lopenctm

$(OPENCTMLIB):
	cd ../src && $(MAKE) -f Makefile.linux && cd ../tools
